Thu Jun  1 12:51:42 UTC 2023
Exception in thread "main" java.lang.RuntimeException: An error occurred when instantiating an object of class: hardwar.branch.prediction.judged.GAg.GAg
null
	at hardwar.branch.prediction.judge.ReflectivePredictorProvider.displayErrorAndExit(ReflectivePredictorProvider.java:22)
	at hardwar.branch.prediction.judge.ReflectivePredictorProvider.getObject(ReflectivePredictorProvider.java:50)
	at hardwar.branch.prediction.judge.ReflectivePredictorProvider.getPredictor(ReflectivePredictorProvider.java:34)
	at hardwar.branch.prediction.judge.Judge.getSimulator(Judge.java:48)
	at hardwar.branch.prediction.judge.Judge.main(Judge.java:31)
GAp: 
Exception in thread "main" hardwar.branch.prediction.judge.TestFailedException: Test failed, 287 out of 1000 assertions passed
	at hardwar.branch.prediction.judge.Judge.main(Judge.java:39)
GAs: 
Exception in thread "main" hardwar.branch.prediction.judge.TestFailedException: Test failed, 203 out of 1000 assertions passed
	at hardwar.branch.prediction.judge.Judge.main(Judge.java:39)
PAg: 
Exception in thread "main" hardwar.branch.prediction.judge.TestFailedException: Test failed, 102 out of 1000 assertions passed
	at hardwar.branch.prediction.judge.Judge.main(Judge.java:39)
PAp: 
Exception in thread "main" hardwar.branch.prediction.judge.TestFailedException: Test failed, 260 out of 1000 assertions passed
	at hardwar.branch.prediction.judge.Judge.main(Judge.java:39)
PAs: 
Exception in thread "main" hardwar.branch.prediction.judge.TestFailedException: Test failed, 262 out of 1000 assertions passed
	at hardwar.branch.prediction.judge.Judge.main(Judge.java:39)
SAg: 
Exception in thread "main" hardwar.branch.prediction.judge.TestFailedException: Test failed, 114 out of 1000 assertions passed
	at hardwar.branch.prediction.judge.Judge.main(Judge.java:39)
SAp: 
Exception in thread "main" hardwar.branch.prediction.judge.TestFailedException: Test failed, 342 out of 1000 assertions passed
	at hardwar.branch.prediction.judge.Judge.main(Judge.java:39)
SAs: 
Exception in thread "main" hardwar.branch.prediction.judge.TestFailedException: Test failed, 257 out of 1000 assertions passed
	at hardwar.branch.prediction.judge.Judge.main(Judge.java:39)
